### PR TITLE
Maintenance 

### PR DESCRIPTION
**Pull request by britannio**
Closes https://github.com/britannio/in_app_review/issues/58
Closes https://github.com/britannio/in_app_review/issues/71

### CODE REVIEW

**Comment by davidmartos96** [comment]
Java dependency `com.google.android.play:review` has been updated to 2.0.1

Is there any update on this? In-app review was not working on my Android device in the internal track, whereas using this PR did.

**Comment by britannio** [comment]
> Java dependency `com.google.android.play:review` has been updated to 2.0.1
> 
> @britannio  Is there any update on this? In-app review was not working on my Android device in the internal track, whereas using this PR did.

Gotcha, I'll get this published by the end of the week, possibly today.

**Comment by davidmartos96** [comment]
@britannio Great! It's possible that #68 gets resolved. Maybe proguard was necessary with the old Play Core package, but now there is a specific dependency for in app review on Android.

**Comment by Oleksandr32** [comment]
hi @britannio, sorry for annoying
Nothing changed, do you still plan to publish the new version this week?

**Comment by alan2030** [comment]
> @britannio Great! It's possible that #68 gets resolved. Maybe proguard was necessary with the old Play Core package, but now there is a specific dependency for in app review on Android.

Not sure if this is the right place, but I am on Flutter 1.22. I think I won't be able to upgrade the library because of that. Do you mind sharing what has been added to fix the issue, so that I can manually implement myself? Also thinking calling in-app-review from Java/Kotlin if this doesn't work out. 

Thank you!

**Comment by davidmartos96** [comment]
@alan2030 You can try changing the Android dependency in tje gradle file to the new one to see if that was the cause.
Before the `com.google.android.play:core` dependency was used. Now there is one specific for the in app reviews `com.google.android.play:review`

**Comment by alan2030** [comment]
> fore the `com.google.android.play:core` dependency was used. Now there is one specific for the in app reviews `com.google.android.play:review`

@davidmartos96 Thank you for you reply! 

I have 2 build.gradle files and it seems that none of them have com.google.android.play:core or com.google.android.play:review 

Which one I should add it to? The one in "android" folder or "app" folder? Its weirds that app review is working on some devices considering project is missing those dependencies.

**Comment by davidmartos96** [comment]
@alan2030 The file is `in_app_review/android/build.gradle`

And the line is `implementation 'com.google.android.play:core:1.10.0'`

**Comment by davidmartos96** [comment]
@britannio Hello! Did something break with the PR? Or are you still planning to merge and update soon?

**Comment by britannio** [comment]
> > @britannio Great! It's possible that #68 gets resolved. Maybe proguard was necessary with the old Play Core package, but now there is a specific dependency for in app review on Android.
> 
> Not sure if this is the right place, but I am on Flutter 1.22. I think I won't be able to upgrade the library because of that. Do you mind sharing what has been added to fix the issue, so that I can manually implement myself? Also thinking calling in-app-review from Java/Kotlin if this doesn't work out.
> 
> Thank you!

Any particular reason for being on such an old version?

**Comment by britannio** [comment]
> @britannio Hello! Did something break with the PR? Or are you still planning to merge and update soon?

Sincere apologies for the delay, it has been merged and published.

**Comment by davidmartos96** [comment]
> > @britannio Hello! Did something break with the PR? Or are you still planning to merge and update soon?
> 
> Sincere apologies for the delay, it has been merged and published.

No worries, thanks for the update!

**Pull request merged**
