### PR TITLE
Adds Android namespace

### PR DESCRIPTION
**Pull request by asaarnak**
Adds a namespace attribute to the Android build.gradle, for compatibility with Android Gradle Plugin 8.0.
See:
https://github.com/flutter/packages/commit/6284c2d4e46a5d289e77cb03a9457543b97f750b

### CODE REVIEW

**Review by devmasteripatas — APPROVED** [review]

**Review by davidmartos96 — APPROVED** [review]

**Comment by britannio** [comment]
> Can we merge this change and release an update?

I'll need to test it out, what's the significance of the change? Is anything broken?

**Comment by cuong0993** [comment]
It will fix the build if using AGP 8.
Build error can be found here https://github.com/cuong0993/issue/blob/master/pubspec.yaml#L39
image

Some popular package already did it.
https://github.com/firebase/flutterfire/commit/a3b967354294c295a9be8d699a6adb7f4b1dba7f
https://github.com/fluttercommunity/plus_plugins/commit/4faa5d8a9c5d3ebbfe16ce30d3a54d25c84b208a

**Comment by asaarnak** [comment]
> > Can we merge this change and release an update?
> 
> I'll need to test it out, what's the significance of the change? Is anything broken?

Shouldn't break anything, just adds AGP 8 support.

**Comment by under3415** [comment]
I was able to build the project with Gradle 8 after referring to this fork in `pubspec.yaml`:

```
in_app_review: 
    git: 
      url: https://github.com/asaarnak/in_app_review.git
      ref: patch-1
      path: in_app_review
```

**Comment by davidmartos96** [comment]
@britannio Any chance to publish a https://pub.dev version with this?

**Comment by AndreaMinato** [comment]
@britannio Can confirm it builds no problem with this changes

**Comment by britannio** [comment]
Thanks for the contribution, this will be published shortly!

**Comment by tp-coderbabu** [comment]
any update for releasing the new version? @britannio

**Comment by britannio** [comment]
> any update for releasing the new version? @britannio 

Yeah, my laptop is in repair until ~Thursday. You can depend on the latest git version until then and I'll leave a comment when the release is out.

**Comment by absar** [comment]
It needs to be released soon, since most of the plugins are upgraded to AGP 8, this plugin is preventing Apps from upgrading

**Pull request merged**
